### ISSUE TITLE
i have a large DVD and Blu-ray collection

### ISSUE THREAD

**Issue by Caesar-1dev** [Project-Bradnails/Bradnails#4]
i can get a wider selection of movies. also I can help with adding some games @ProjectBradnails

**Comment by Caesar-1dev** [comment]
wait put wrong flair
also cant figure out how to change flair

**Comment by ProjectBradnails** [comment]
Hello @Memer-man, thanks for reaching out, we are glad you're interested in the project. Could you share some examples of the content you have to us, so that we can see what you have to offer. We would prefer that all our content is on Google drives, as it is a generally safe website to host off of, although we can make compromises. (Note: Quick question, will the end user have to torrent this to access it? If so, just let me know.)

Best regards, 
Stansfield Mozart

**Comment by Caesar-1dev** [comment]
I can.  I don't use google drive mainly because my school uses OneDrive. The end user will have to use a torrent, but I've been using it for the past 3 years or so, or we can download the movies and you can move them to google drive. I also have all of the top gear episodes w/ the OG members along with TGT that i am keeping updated. i put these on an Mega like site because it it a total of 65 ish GB.(they are also neatly ordered and you can "preview" them on the site. Add me on discord so we can communicate better. Memer#4111 @ProjectBradnails

**Comment by ProjectBradnails** [comment]
@Memer-man Thank you, we are interested, I will add you on discord so that we can communicate there. My @ is Stansfield Mozart#9932. Additionally, I think it would be best if we torrented the content before uploading it to bradnails, as the process of torrenting and do so safely could be a bit complicated for the everyday user.

**Comment by avourr** [comment]
Hi, completely irrelvant topic to what was being said above but. When are you guys plannng on adding new games as i would like to see some new games. You are pretty much inactive but it will be nice seeing some new games added. Much love <3
